### ISSUE TITLE
Minetype loading warning warning with actionpack

### ISSUE THREAD

**Issue by cerias** [RCRM/redmine_people#5]
We getting an warning from the people plugin and the concacts plugin. 

".../2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/http/mime_type.rb:163  warning: already initialized constant Mime::VCF"

We could get rid of the warnings with checking if mimetype is already set. 

    Mime::Type.register "text/x-vcard", :vcf unless Mime::Type.lookup_by_extension(:vcf)

**Comment by sergeyz** [comment]
This is an automatically updated unofficial mirror of the RedmineCRM (http://redminecrm.com/) plugins
