### ISSUE TITLE
Internal Server error 500 on people main page

### ISSUE THREAD

**Issue by cheoAlejo** [RCRM/redmine_people#6]
I'm having this error for versions `> 1.0.0` of the plugin. With version 1.0.0 works fine.

`production.log` :
```
Started GET "/people" for xxx.xxx.xxx.xxx at 2016-01-05 01:13:33 -0500
Processing by PeopleController#index as HTML
  Current user: sergioal65 (id=6)
Completed 500 Internal Server Error in 343ms (ActiveRecord: 13.1ms)

NoMethodError (undefined method `each' for nil:NilClass):
  app/models/query.rb:367:in `available_filters'
  app/models/query.rb:247:in `build_from_params'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**My Environment:**

```
  Redmine version                3.2.0.stable
  Ruby version                   2.0.0-p643 (2015-02-25) [i686-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
```

**Comment by Haixing-Hu** [comment]
I got the same error.

**Comment by adrianobr** [comment]
+1

**Comment by illuminated** [comment]
same here
Environment:
  Redmine version                3.2.0.stable.15058
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               PostgreSQL

**Comment by adrianobr** [comment]
Hello guys,
I was with the above problem, solved going into administration> people> marking options, create departments etc.
After people go to the page.

**Comment by DarkSideGeek** [comment]
I reported similar at the RCRM company page. They gave me the 'Pro' upgrade to test out, which I thought solved the problem. But for some reason, it was only temporary. The error is back again on 2.6.9.

And I concur with @cheoAlejo thast the 1.0.0 version seems to be OK...

**Comment by Silverjack** [comment]
Same problem here, my environment is :
Environment:
  Redmine version                3.0.3.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2

The previous version was working fine.

**Comment by justine** [comment]
+1, same error here.
Environment:
Redmine version                3.0.7.stable
Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
Rails version                  4.2.3
Environment                    production
Database adapter               Mysql2

The previous version of Redmine I used (2.6.1), it was working fine.

**Comment by vvklymchuk-trade-active** [comment]
+1
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [i386-mingw32]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2

**Comment by sergeyz** [comment]
Please try 1.2.0 version https://github.com/RCRM/redmine_people/tree/v1.2.0

**Comment by sergeyz** [comment]
http://www.redminecrm.com/questions
